spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test
    username: root
    password: YOUR_PASSWORD
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  logging:
    level:
      org:
        springframework:
          web: DEBUG
          r2dbc: DEBUG
          transaction: DEBUG
  cloud:
    stream:
      kafka:
        binder:
          brokers: pkc-gq2xn.asia-northeast3.gcp.confluent.cloud:9092
          configuration:
            security:
              protocol: SASL_SSL
            sasl:
              jaas:
                config: org.apache.kafka.common.security.plain.PlainLoginModule required username='YOUR_USER_NAME' password='YOUR_SECRET_KEY';
              mechanism: PLAIN
            client:
              dns:
                lookup: use_all_dns_ips
          required-acks: all
          auto-create-topics: false
        bindings:
          send-out-0:
            producer:
              record-metadata-channel: payment-result
      bindings:
        send-out-0:
          destination: payment
          group: payment-service

PSP:
  toss:
    secretKey: YOUR_SECRET_KEY
    url: https://api.tosspayments.com

management:
  endpoints:
    web:
      exposure:
        include: bindings
