spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test
    username: root
    password: [ YOUR_PASSWORD ]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

PSP:
  toss:
    secretKey: [ YOUR_KEY ]
    url: https://api.tosspayments.com